# compose for CI/CD

services:
  app-name:
    build:
      context: ..
      dockerfile: .github/Dockerfile
    tty: true   # * will keep container running so we can execute commands on it -- this is needed for testing in pipeline
    container_name: app-name-container
