name: checks

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'scripts/*'
      - 'imgs/*'
      - 'LICENSE'
      - '.env.example'

jobs:
  checks:
    runs-on: ubuntu-latest

    env:
      DEVCONTAINER_COMPOSE_PATH: ./.github/docker-compose.yml
      EXECUTE_IN_CONTAINER: docker exec app-name-container

    steps:
    - uses: actions/checkout@v3

    - name: build and run compose for testing
      run: docker-compose -f $DEVCONTAINER_COMPOSE_PATH up -d

    - name: check formatting (ruff)
      run: $EXECUTE_IN_CONTAINER ruff format --check

    - name: check linting (ruff)
      run: $EXECUTE_IN_CONTAINER ruff check

    - name: check typing (mypy)
      run: $EXECUTE_IN_CONTAINER mypy .

    - name: test with pytest
      run: $EXECUTE_IN_CONTAINER coverage run -m pytest .

    - name: check coverage with coveragepy 
      run: $EXECUTE_IN_CONTAINER coverage report -m

    - name: Down compose
      run: docker-compose -f $DEVCONTAINER_COMPOSE_PATH down
